### ISSUE TITLE
Issues and Suggest

### ISSUE THREAD

**Issue by NelsonHD** [FabioZumbi12/UltimateChat#130]
Platform: Spigot 1.12.2

Jar version: UltimateChat-1.8.6-b192-Universal.jar

Minecraft version: 1.12.2

What you want?: issues and suggest

Description:

1. I got an error when i try to connect to redis , I tried to set with bind 0.0.0.0 and Protect Mode false , 
   still got error on it , tested on Ubuntu https://hastebin.com/laqanupaxi.md 
2. Cant type the single word, such as "u" "y" "?"
3. /chat ignore player is not working
4. The mention is not working
5. Cant reply msg ( "/r" ) from redis server and lock the /m mode (not at same server)
6. Would you like to make Discord log/tell/commands channel customer format ?
P.S Thank you for your help to deal with these issues, we're glad to donate for buy you a cup of coffee :wink:

**Comment by FabioZumbi12** [comment]
1. Redis server with default config valus should work (works for most people using redis);
2. Its because channel listener `like /g, /l` and is a know issue where i need to look for a solution.
3. Chat ignore is working, the usage is `/chat ignore player <player name>`
4. Mention is working too, dont know why is not working for you (permisisons?)
5. Its a limitation where i dont wnat to work for now. As you see, its too hard to work with redis.
6. You already can allow discord channel to send command to minecraft, just see the uchat channel file and enable receive commands option, and enable this channel on config.yml/.conf.
