### ISSUE TITLE
Plugin wont load on Server start

### ISSUE THREAD

**Issue by AokuYuki** [FabioZumbi12/UltimateChat#141]
If you are running the plugin at first time, try to run again to see if the problem persists.
**I restarted the server muliple times.**

I am using:  
* spongeforge-1.12.2 
* spongeapi 7.1.0-SNAPSHOT-f28d4ba
* UltimateChat-1.8.6-b192-Universal.jar

 
Minecraft version:  1.12.2

_Issue_  
Plugin does not start correctly. Config file stays empty.

Error:  
`[20:36:46] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UChat:onServerStart:186]: java.lang.IllegalArgumentException: Configuration does not accept objects of type class br.net.fabiozumbi12.UltimateChat.Sponge.config.MainCategory
`

Complete error message:
 https://hastebin.com/etocafacup.md

**Comment by MrXromik** [comment]
I also have it

**Comment by Deathinflames** [comment]
I just tried loading UltimateChat-1.8.6-b192-Universal.jar with forge-1.12.2-14.23.4.2739-universal.jar and it generates the files just fine. Are you sure you have the UltimateChat-JDA.jar file in your mods folder as well?

**Comment by AokuYuki** [comment]
I tried it with the UltimateChat-1.8.6-b192-Universal.jar within the Folder "mods" and "mods/plugins"
When in the "mods" folder i get this error:

```
[08:48:27] [Server thread/INFO] [minecraft/DedicatedServer]: UltimateChat: [-> Config module]
[08:48:27] [Server thread/INFO] [minecraft/DedicatedServer]: UltimateChat: [Creating config file...]
[08:48:27] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UChat:onServerStart:199]: java.lang.IllegalArgumentException: Configuration does not accept objects of type class br.net.fabiozumbi12.UltimateChat.Sponge.config.MainCategory
...
```
https://hastebin.com/equmuramij.md

When within the "mods/plugins" i get the error i postet above.

In both cases i get a empty config file.

**Comment by Deathinflames** [comment]
You still didn't mention if you put the **UltimateChat-JDA.jar** in the "mods" folder.

Get it from here: https://host.areaz12server.net.br:8080/job/UltimateChat/

**Comment by AokuYuki** [comment]
Ah sorry i didnt get that you meant another file! 
I need two files for UltimateChat to work?

I got UltimateChat from here: https://ore.spongepowered.org/FabioZumbi12/UltimateChat
And there is nowhere written that UltimateChat requires an additional file to work, so i dont have this file anywhere in my mods folder. 

I Just have UltimateChat-1.8.6-b192-Universal.jar since i thought universal means i dont need anything additional.

**Comment by Deathinflames** [comment]
No, the UltimateChat-JDA.jar is a soft dependency which means it's optional but you should probably add it anyways since you will most likely need it once you manage to get the plugin to work and start to configure it. The developer also recommends using the latest dev builds that way it eliminates the most common issues that people seek help for.

We also don't know exactly what build of forge and spongeforge you are running, you just said "spongeforge-1.12.2". In my previous replies i mentioned exactly what builds the plugin works with for me, perhaps match those build numbers in your troubleshooting?

If you continue to have issues after that then the last thing is uploading your FULL server log to https://pastebin.com/ so we can better diagnose the issue.

**Comment by AokuYuki** [comment]
I am sorry that I expressed myself so vaguely. 
I am using: 
spongeforge-1.12.2-2705-7.1.0-BETA-3322.jar

Unfortunally i continue to have issues.

Here a full server startup log:
https://pastebin.com/R960DLvU

I restarted the server 4 times, after i added the **UltimateChat-JDA.jar** file.

**Comment by FabioZumbi12** [comment]
Fixed on latest versions.
